"""Update Like Model.

Revision ID: 3494b3c7f90b
Revises: 7e89f394214b
Create Date: 2023-11-21 00:18:07.380856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3494b3c7f90b"
down_revision = "7e89f394214b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=50),
            existing_nullable=False,
        )
        batch_op.drop_constraint("likes_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["public_id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "likes_user_id_fkey", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.String(length=50),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
