"""Update Like Model 2.

Revision ID: fcd5c0f007f5
Revises: 3494b3c7f90b
Create Date: 2023-11-22 15:04:00.622704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcd5c0f007f5"
down_revision = "3494b3c7f90b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_constraint("likes_post_id_key", type_="unique")
        batch_op.create_unique_constraint(None, ["user_id", "post_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint("likes_post_id_key", ["post_id"])

    # ### end Alembic commands ###
